### ISSUE TITLE
typo fix in /Usage.tsx

### ISSUE THREAD

**Issue by diomed** [AcidOP/potterhead-api#7]
hey

you have few typos in homepage of app

**specefic** should say **specific**

just replace. coz this is all over the place

**Comment by SpandanSehgal** [comment]
Thanks @diomed , for letting us know the issue. 
We will surely fix the typos.

Thank you 🙂

**Comment by AcidOP** [comment]
@diomed hey thanks for letting us know.
I have fixed this.
